### ISSUE TITLE
How to use it for drupal?

### ISSUE THREAD

**Issue by ugintl** [Junker/JSendResponse#1]
How to use it for drupal?

**Comment by artyuum** [comment]
Late reply but I'm using it in Drupal and I don't have any issue at all. You simply need to return an instance of `JsendResponse` in your controller (which extends from `JsonResponse`):
```php
return new JsendResponse(JSendResponse::STATUS_SUCCESS, $data);
#or
return new JsendResponse(JSendResponse::STATUS_FAIL, $data);
#or 
return new JsendResponse(JSendResponse::STATUS_ERROR, NULL, $message);
#or
return new JsendResponse(JSendResponse::STATUS_ERROR, $data, $message, $code);
#or
return new JsendSuccessResponse($data);
#or
return new JsendFailResponse($data);
#or
return new JsendErrorResponse($message);
#or
return new JsendErrorResponse($message, $code, $data);
```
@Junker this should closes the issue.

**Comment by ugintl** [comment]
So late that I forgot why I landed on this repository. Can you tell me what it is used for in drupal?

**Comment by artyuum** [comment]
It's not specifically used in Drupal. This library helps you to build a response that follows the [JSend specification](https://github.com/omniti-labs/jsend). This library only works with applications that use the Symfony HTTP Foundation component (e.g. Symfony, Drupal, etc.) in order to build the response.  

I'm currently using it to have a consistent response across all of my controllers in my Symfony app but also in a custom Drupal module we are making at work.
